name: Tox tests

on: [push, pull_request]
jobs:
  py39:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py39 -vv
        
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e black -vv
        
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e flake8 -vv
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py39
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: true
          verbose: true
          directory: ./coverage/reports/
          files: ./coverage.xml
          name: codecov-umbrella
